apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: postgresql
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: liquid-voting-postgres-config
              key: postgres-dbname
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: liquid-voting-postgres-config
              key: postgres-username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: liquid-voting-postgres-config
              key: postgres-password
        image: postgres:10.4
        imagePullPolicy: "IfNotPresent"
        name: db
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: data
          subPath: liquid-voting
      hostname: db
      restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-pvc
