apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: liquid-voting-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/rewrite-target: /
    prometheus.io/scrape: "true"
    prometheus.io/port: "10254"
spec:
  rules:
  - http:
      paths:
        - path: /
          backend:
            serviceName: liquid-voting-service
            servicePort: 4000
