apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: liquid-voting-ingress
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: /
          backend:
            serviceName: liquid-voting
            servicePort: 80
