apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata: 
  name: letsencrypt-issuer
spec: 
  acme: 
    email: oli.azevedo.barnes@gmail.com
    server: "https://acme-v02.api.letsencrypt.org/directory"
    privateKeySecretRef: 
      name: letsencrypt
    solvers:
    - http01:
        ingress:
          class: nginx
