name: Manually triggered smoke-tests of api

on:
  workflow_dispatch:

jobs:
  smoke_tests:
    name: Smoke Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run k6 votes smoke test
      uses: k6io/action@v0.1
      env:
        TEST_API_AUTH_KEY: ${{ secrets.TEST_API_AUTH_KEY }}
      with:
        filename: smoke_tests/votes_test.js
    - name: Run k6 delegations smoke test
      uses: k6io/action@v0.1
      env:
        TEST_API_AUTH_KEY: ${{ secrets.TEST_API_AUTH_KEY }}
      with:
        filename: smoke_tests/delegations_test.js
    - name: Run k6 participants smoke test
      uses: k6io/action@v0.1
      env:
        TEST_API_AUTH_KEY: ${{ secrets.TEST_API_AUTH_KEY }}
      with:
        filename: smoke_tests/participants_test.js
    - name: Run k6 voting results smoke test
      uses: k6io/action@v0.1
      env:
        TEST_API_AUTH_KEY: ${{ secrets.TEST_API_AUTH_KEY }}
      with:
        filename: smoke_tests/voting_results_test.js
    - name: Login to gcloud
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.GKE_EMAIL }}
        service_account_key: ${{ secrets.GKE_KEY }}
    - name: Teardown smoke test data
      env:
        GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
        GKE_ZONE: ${{ secrets.GKE_ZONE }}
        GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $GKE_PROJECT
        pod=$(kubectl get pods -l app=api  -o json | jq -r '.items[].metadata.name' | head -1)
        kubectl wait --timeout=120s --for=condition=Ready pod/$pod
        kubectl exec -ti pod/$pod \
        --container api-container \
        -- /opt/app/bin/liquid_voting \
        eval "LiquidVoting.Release.smoke_test_teardown"